### ISSUE TITLE
Tests deadlock on master

### ISSUE THREAD

**Issue by laszlocph** [laszlocph/drone-oss-08#20]
The behavior is nondeterministic, but happens often that unit tests deadlock on master

Examples:
https://cloud.drone.io/laszlocph/drone-oss-08/40/1/4
https://cloud.drone.io/laszlocph/drone-oss-08/30

Then rebuilds succeed:
https://cloud.drone.io/laszlocph/drone-oss-08/41/1/4

**Comment by AkiraNorthstar** [comment]
Here some links about deadlock:
[Detect Deadlock](https://yourbasic.org/golang/detect-deadlock/)
[all goroutines are asleep - deadlock!](https://github.com/golang/go/issues/22424)

I'm currently testing golang 1.12 as base image - and so far this bug has not happened yet.
And I hope that it stays that way ;-)

**Comment by laszlocph** [comment]
I bumped master to use Go 1.12.

Only a handful of builds ran since, but the issue didn't happen.

:crossed_fingers:

**Comment by laszlocph** [comment]
So it's happening with Go 1.12 too. This is just a feeling but it's more frequent if many Drone builds run in parallel. Can't be true since they are just channels.. but this is what I sense :crying_cat_face:

**Comment by laszlocph** [comment]
The deadlocking tests are timing sensitive. 1ms wait is not enough in some cases. An excessive solution (500ms wait) is applied now. Merging to master if it works in the coming week: https://github.com/laszlocph/drone-oss-08/commit/f386c4fca339085b50d227111170913cc8f45387

**Comment by laszlocph** [comment]
That was it. Now it's merged.
