### ISSUE TITLE
Update Readme with information about fork

### ISSUE THREAD

**Issue by kevinsimper** [laszlocph/drone-oss-08#29]
It would be great to know if all the code is together or if there is multiple forked repositories :)

**Comment by laszlocph** [comment]
Thanks for the issue.

I think to best answer this question, head over to https://github.com/laszlocph/drone-oss-08/blob/master/vendor/vendor.json where all the dependencies are listed.

On top of that 
- all `github.com/drone/` repos have been forked, although references were not updated in the vendor file.
- some dependencies were pulled in the project to allow faster iteration: https://github.com/laszlocph/drone-oss-08/pull/12

I added some info on the project in this PR. https://github.com/laszlocph/drone-oss-08/pull/30

**Comment by laszlocph** [comment]
I keep this issue open as the Readme.md is far from what it should be.
