### ISSUE TITLE
[drone-ui] SVG files inside programm code

### ISSUE THREAD

**Issue by AkiraNorthstar** [laszlocph/drone-oss-08#31]
Is there a way in [drone-ui](https://github.com/laszlocph/drone-ui) to use the graphics as a standalone "xxx.svg", or do they have to be in the program code?
It would be easier to maintain.

Sorry to post this here, no issues can be created in your drone-ui repo.

**Comment by laszlocph** [comment]
I opened issues now on that repo :) Thanks for making me aware.

svg files could be factored into files. I'm not sure the reasoning behind the current setup.

That said, it's not too often that svg's are touched, so I wouldn't spend time right now to restructure.

**Comment by AkiraNorthstar** [comment]
> That said, it's not too often that svg's are touched, so I wouldn't spend time right now to restructure.

You're right, that these graphics are rarely changed.
You do not need to change this, that was a question of understanding.
I did not know if it's common in GO to mix program code with "graphicscode".
Many thanks for your response!

I close this entry because all questions are answered and it does not belong to drone-oss-08 directly.
