### ISSUE TITLE
Bitbucket is broken as v1 API deprecated

### ISSUE THREAD

**Issue by laszlocph** [laszlocph/drone-oss-08#34]
https://discourse.drone.io/t/drone-0-8-broken-due-to-bitbucket-v1-api-being-decommissioned/4816/8

**Comment by laszlocph** [comment]
Although my focus is on Github, I make a stab at this. Will update this in 24hrs.

**Comment by laszlocph** [comment]
This is an attempt to fix the issue. Worked with my basic tests.

https://github.com/laszlocph/drone-oss-08/pull/35

**Comment by laszlocph** [comment]
I'm waiting for someone to confirm that the fix works. 

The images can be pulled from:

laszlocloud/drone-oss-08-agent:0.8.95-bitbucket
laszlocloud/drone-oss-08-server:0.8.95-bitbucket

**Comment by saward** [comment]
A preliminary test suggests that this does indeed work.  I'll post an update here if I run into any issues.  Could you please post here if/when you merge this into the main branch?

Thanks!

**Comment by laszlocph** [comment]
Based on the two ping backs from users, this issue seem to be fixed and part of the master since  https://github.com/laszlocph/drone-oss-08/releases/tag/v0.8.101

**Comment by saward** [comment]
Sorry, I forgot to update, I think that this is not triggering for tags.  However, this is based on me using the two images posted above, so I haven't tested with the latest.
